#!/usr/bin/env python3
"""Generate the visual roadmap SVG from map data (see docs/briefs/visual-roadmap.md).

Usage: python3 scripts/roadmap-gen.py            # regenerates the SVG inside roadmap.md
The map is data (scripts/roadmap-map.json); the picture is a generated view of it.
Drawn in the site diagram language (scripts/isokit.py): built is a solid orange line,\npartial dashed, planned dotted grey.
"""
import json
import html
import os

import re
import sys
sys.path.insert(0, os.path.dirname(__file__))
from isokit import CSS, Iso, plate, text_on, leader  # noqa: E402

W = 760
CX = W // 2
PW = 210          # plate length along its x axis (the stage title runs this way)
THICK = 6
STAGE_GAP = 16    # vertical space between one plate's bottom and the next plate's top
LX_LEFT, LX_RIGHT = 186, 576   # where the branch labels' leaders end
CIRCLED = dict(zip("⓪①②③④⑤⑥⑦⑧⑨", "0123456789"))
EMOJI = re.compile("[\U0001F000-\U0001FFFF\u2600-\u27BF\u2B00-\u2BFF\uFE0F\u2728]")


def clean(label):
    """Drop emoji; the diagram is mono type and orange line, nothing else."""
    return EMOJI.sub("", label).strip()


def main():
    here = os.path.dirname(__file__)
    data = json.load(open(os.path.join(here, "roadmap-map.json")))
    parts, y = [], 24
    for stage in data["stages"]:
        branches = stage.get("branches", [])
        left = [b for b in branches if b.get("side") == "left"]
        right = [b for b in branches if b.get("side") != "left"]
        k = max(len(left), len(right), 1)
        pd = max(120, 36 * (k + 1))                # plate depth grows with its branches
        iso = Iso(CX - (PW - pd) * 0.866 / 2, y)   # centre the plate on the page
        status = stage["status"]
        title = clean(stage["label"])
        num = CIRCLED.get(title[:1], "")
        title = title[1:].strip() if num else title
        lines = title.split("\\n")
        g = [plate(iso, PW, pd, 0, THICK)]
        if num:
            g.append(text_on(iso, 18, 34, 0, num, 30, "num"))
        for i, line in enumerate(lines):
            g.append(text_on(iso, 18, 56 + i * 17, 0, html.escape(line), 12.5))
        parts.append(f'<a href="{stage["url"]}"><g class="{status}">{"".join(g)}</g></a>')
        for side, items in (("L", left), ("R", right)):
            for i, b in enumerate(items):
                yy = pd * (i + 1) / (len(items) + 1)
                px, py = iso.P(0, yy) if side == "L" else iso.P(PW, yy)
                lx = LX_LEFT if side == "L" else LX_RIGHT
                lab = leader(px, py, lx, html.escape(clean(b["label"])), side)
                parts.append(f'<a href="{b["url"]}"><g class="{b["status"]}">{lab}</g></a>')
        y += (PW + pd) * 0.5 + THICK + STAGE_GAP
    y -= STAGE_GAP - 24
    spine = f'<line class="spine" x1="{CX}" y1="40" x2="{CX}" y2="{y - 60:.0f}"/>'
    svg = (f'<svg class="ik" viewBox="0 0 {W} {y:.0f}" xmlns="http://www.w3.org/2000/svg" role="img" '
           f'aria-label="The Markdown Roadmap: seven stages from why bother to build your thing, each with side trips" '
           f'style="width:100%;height:auto;max-width:{W}px">'
           f'<style>{CSS}</style>{spine}{"".join(parts)}</svg>')
    block = f"""<!-- ROADMAP-SVG-START (generated by scripts/roadmap-gen.py from scripts/roadmap-map.json — edit the data, then regenerate; do not edit the SVG by hand) -->
<div style="overflow-x:auto">
{svg}
</div>
<!-- ROADMAP-SVG-END -->"""
    out = os.path.join(here, "..", "roadmap.md")
    page = open(out).read()
    import re as _re
    new = _re.sub(r"<!-- ROADMAP-SVG-START.*?<!-- ROADMAP-SVG-END -->", lambda m: block, page, flags=_re.S)
    assert "ROADMAP-SVG-START" in new, "markers missing in roadmap.md"
    open(out, "w").write(new)
    print(f"updated roadmap.md ({y:.0f}px tall, {sum(len(s.get('branches', [])) + 1 for s in data['stages'])} nodes)")


if __name__ == "__main__":
    main()
