#!/usr/bin/env python3
"""Generate the visual roadmap SVG from map data (see docs/briefs/visual-roadmap.md).

Usage: python3 scripts/roadmap-gen.py            # writes x-roadmap-experiment.md
The map is data (scripts/roadmap-map.json); the picture is a generated view of it.
Status colours: built (solid green), partial (dashed amber), planned (dotted grey).
"""
import json
import html
import os

W = 920
CX = W // 2
SPINE_W, SPINE_H = 270, 58
BR_W, BR_H = 205, 42
STAGE_GAP = 40
BR_GAP = 12
BR_XOFF = 90  # gap between spine box edge and branch cluster

STATUS_STYLE = {
    "built":   'class="rm-node rm-built"',
    "partial": 'class="rm-node rm-partial"',
    "planned": 'class="rm-node rm-planned"',
}

CSS = """
  .rm-node rect { fill: rgba(34,197,94,0.10); stroke: #22c55e; stroke-width: 2; }
  .rm-partial rect { fill: rgba(245,158,11,0.10); stroke: #f59e0b; stroke-dasharray: 7 4; }
  .rm-planned rect { fill: rgba(148,163,184,0.10); stroke: #94a3b8; stroke-dasharray: 2 4; }
  .rm-node text { fill: currentColor; font: 600 15px system-ui, sans-serif; }
  .rm-branch text { font-weight: 500; font-size: 13px; }
  .rm-edge { fill: none; stroke: #94a3b8; stroke-width: 1.5; opacity: 0.7; }
  .rm-spine-edge { fill: none; stroke: #64748b; stroke-width: 3; }
  .rm-node:hover rect { stroke-width: 3.5; }
"""


def node(x, y, w, h, label, url, status, branch=False):
    cls = STATUS_STYLE[status]
    extra = " rm-branch" if branch else ""
    cls = cls.replace('rm-node', 'rm-node' + extra)
    lines = label.split("\\n")
    tspans = ""
    n = len(lines)
    for i, line in enumerate(lines):
        dy = y + h / 2 + (i - (n - 1) / 2) * 16 + 5
        tspans += f'<text x="{x + w / 2}" y="{dy:.0f}" text-anchor="middle">{html.escape(line)}</text>'
    rect = f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="10"/>'
    return f'<a href="{url}">{f"<g {cls}>"}{rect}{tspans}</g></a>'


def edge(x1, y1, x2, y2, spine=False):
    cls = "rm-spine-edge" if spine else "rm-edge"
    if spine:
        return f'<path class="{cls}" d="M {x1} {y1} L {x2} {y2}"/>'
    mx = (x1 + x2) / 2
    return f'<path class="{cls}" d="M {x1} {y1} C {mx} {y1}, {mx} {y2}, {x2} {y2}"/>'


def main():
    here = os.path.dirname(__file__)
    data = json.load(open(os.path.join(here, "roadmap-map.json")))
    parts, y = [], 30
    for stage in data["stages"]:
        left = [b for b in stage.get("branches", []) if b.get("side") == "left"]
        right = [b for b in stage.get("branches", []) if b.get("side") != "left"]
        cluster_h = max(len(left), len(right)) * (BR_H + BR_GAP) - BR_GAP if (left or right) else 0
        stage_h = max(SPINE_H, cluster_h)
        sy = y + (stage_h - SPINE_H) / 2
        if parts:  # spine connector from previous stage
            parts.append(edge(CX, prev_bottom, CX, sy, spine=True))
        parts.append(node(CX - SPINE_W / 2, sy, SPINE_W, SPINE_H, stage["label"], stage["url"], stage["status"]))
        prev_bottom = sy + SPINE_H
        for side, items in (("left", left), ("right", right)):
            by = y + (stage_h - (len(items) * (BR_H + BR_GAP) - BR_GAP)) / 2 if items else 0
            for b in items:
                bx = CX - SPINE_W / 2 - BR_XOFF - BR_W if side == "left" else CX + SPINE_W / 2 + BR_XOFF
                ex1 = CX - SPINE_W / 2 if side == "left" else CX + SPINE_W / 2
                ex2 = bx + BR_W if side == "left" else bx
                parts.append(edge(ex1, sy + SPINE_H / 2, ex2, by + BR_H / 2))
                parts.append(node(bx, by, BR_W, BR_H, b["label"], b["url"], b["status"], branch=True))
                by += BR_H + BR_GAP
        y += stage_h + STAGE_GAP
    svg = (f'<svg viewBox="0 0 {W} {y}" xmlns="http://www.w3.org/2000/svg" role="img" '
           f'aria-label="The Markdown Roadmap" style="width:100%;height:auto;max-width:{W}px">'
           f'<style>{CSS}</style>{"".join(parts)}</svg>')
    page = f"""---
title: "Roadmap experiment (visual)"
description: "Experimental roadmap.sh-style visual map of the way of markdown. Generated page — do not edit by hand."
---

# The Markdown Roadmap — visual experiment 🧪

> [!warning]
> Experiment (see docs/briefs/visual-roadmap.md). Generated by `scripts/roadmap-gen.py` from `scripts/roadmap-map.json` — **edit the data, not this page**. The stable version is [/roadmap](roadmap.md).

**Legend**: <span style="color:#22c55e">■ built</span> · <span style="color:#f59e0b">▧ partial</span> · <span style="color:#94a3b8">□ planned</span> — every box is clickable.

<div style="overflow-x:auto">
{svg}
</div>
"""
    out = os.path.join(here, "..", "x-roadmap-experiment.md")
    open(out, "w").write(page)
    print(f"wrote {os.path.normpath(out)} ({y}px tall, {sum(len(s.get('branches', [])) + 1 for s in data['stages'])} nodes)")


if __name__ == "__main__":
    main()
