#!/usr/bin/env python3
"""Generate the visual roadmap SVG from map data (see docs/briefs/visual-roadmap.md).

Usage: python3 scripts/roadmap-gen.py            # regenerates the SVG inside roadmap.md
The map is data (scripts/roadmap-map.json); the picture is a generated view of it.
Drawn in the map mode of the site diagram language (scripts/isokit.py): built is a
solid orange line, partial dashed, planned dotted grey. The earlier isometric
version is backed up in docs/brand/diagrams/roadmap-iso-2026-10-03/.
"""
import json
import html
import os

import re
import sys
sys.path.insert(0, os.path.dirname(__file__))
from isokit import CSS, box, wire  # noqa: E402

# Map mode (docs/brand/diagram-language.md): a heavy orange rail down the
# middle with the stages on it; optional side trips in lighter boxes either
# side, joined by dotted right-angled wires.
W = 1000
CX = W // 2
SPINE_W, SPINE_H = 260, 58
BR_W, BR_H = 200, 38
STAGE_GAP = 44
BR_GAP = 10
BR_XOFF = 70  # gap between a stage box and its side trips
CIRCLED = dict(zip("⓪①②③④⑤⑥⑦⑧⑨", "0123456789"))
EMOJI = re.compile("[\\U0001F000-\\U0001FFFF\\u2600-\\u27BF\\u2B00-\\u2BFF\\uFE0F\\u2728]")


def clean(label):
    """Drop emoji; the diagram is mono type and orange line, nothing else."""
    return EMOJI.sub("", label).strip()


def main():
    here = os.path.dirname(__file__)
    data = json.load(open(os.path.join(here, "roadmap-map.json")))
    wires, boxes, y = [], [], 24
    first_mid = last_mid = None
    for stage in data["stages"]:
        branches = stage.get("branches", [])
        left = [b for b in branches if b.get("side") == "left"]
        right = [b for b in branches if b.get("side") != "left"]
        n = max(len(left), len(right))
        cluster_h = n * (BR_H + BR_GAP) - BR_GAP if n else 0
        stage_h = max(SPINE_H, cluster_h)
        sy = y + (stage_h - SPINE_H) / 2
        mid = sy + SPINE_H / 2
        first_mid = mid if first_mid is None else first_mid
        last_mid = mid
        title = clean(stage["label"])
        num = CIRCLED.get(title[:1])
        title = title[1:].strip() if num else title
        lines = [html.escape(t) for t in title.split("\\n")]
        boxes.append(f'<a href="{stage["url"]}">'
                     f'{box(CX - SPINE_W / 2, sy, SPINE_W, SPINE_H, lines, "stop " + stage["status"], num)}</a>')
        for side, items in (("left", left), ("right", right)):
            by = y + (stage_h - (len(items) * (BR_H + BR_GAP) - BR_GAP)) / 2
            for b in items:
                bx = CX - SPINE_W / 2 - BR_XOFF - BR_W if side == "left" else CX + SPINE_W / 2 + BR_XOFF
                x1 = CX - SPINE_W / 2 if side == "left" else CX + SPINE_W / 2
                x2 = bx + BR_W if side == "left" else bx
                wires.append(wire(x1, mid, x2, by + BR_H / 2))
                lab = [html.escape(clean(b["label"]))]
                boxes.append(f'<a href="{b["url"]}">{box(bx, by, BR_W, BR_H, lab, "side-stop " + b["status"], size=13)}</a>')
                by += BR_H + BR_GAP
        y += stage_h + STAGE_GAP
    y -= STAGE_GAP - 24
    rail = f'<line class="rail" x1="{CX}" y1="{first_mid:.1f}" x2="{CX}" y2="{last_mid:.1f}"/>'
    svg = (f'<svg class="ik ik-map" viewBox="0 0 {W} {y:.0f}" xmlns="http://www.w3.org/2000/svg" role="img" '
           f'aria-label="The Markdown Roadmap: seven stages on a central line, each with optional side trips" '
           f'style="width:100%;height:auto">'
           f'<style>{CSS}</style>{rail}{"".join(wires)}{"".join(boxes)}</svg>')
    block = f"""<!-- ROADMAP-SVG-START (generated by scripts/roadmap-gen.py from scripts/roadmap-map.json — edit the data, then regenerate; do not edit the SVG by hand) -->
<div class="ik-wide">
{svg}
</div>
<!-- ROADMAP-SVG-END -->"""
    out = os.path.join(here, "..", "roadmap.md")
    page = open(out).read()
    import re as _re
    new = _re.sub(r"<!-- ROADMAP-SVG-START.*?<!-- ROADMAP-SVG-END -->", lambda m: block, page, flags=_re.S)
    assert "ROADMAP-SVG-START" in new, "markers missing in roadmap.md"
    open(out, "w").write(new)
    print(f"updated roadmap.md ({y:.0f}px tall, {sum(len(s.get('branches', [])) + 1 for s in data['stages'])} nodes)")


if __name__ == "__main__":
    main()
